spring.application.name=brunofragadev


# configuracao do JPA Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# habilitar Swagger UI
springdoc.swagger-ui.enabled=true

# definir o caminho do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Caminho da documentacao OpenAPI
springdoc.api-docs.path=/v3/api-docs

# Escanear pacotes do projeto
springdoc.packages-to-scan=com.brunofragadev

# JTW CONFIG
jwt.secret.key=${JWK_KEY:SuaChaveJWTSuperLongaESeguraGeradaEmBase64ParaTestesLocais123456789}
jwt.expiration.ms=3600000

#Banco de Dados PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nome_do_seu_banco}
spring.datasource.username=${DB_USERNAME:brunofdev}
spring.datasource.password=${DB_PASSWORD:123321123321123321}
spring.datasource.driver-class-name=org.postgresql.Driver

#BREVO
brevo.api.key=${BREVO_API_KEY:sua_chave_de_testes_aqui}
brevo.sender.email=${BREVO_SENDER_EMAIL:brunofragaa97@gmail.com}