version: '3.8'
services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: postgres-webportifolio
    environment:
      POSTGRES_DB: webportifolio_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432" # Permite acessar o banco pelo DBeaver/PgAdmin no seu PC
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d webportifolio_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço da API Spring Boot
  api:
    build: .
    container_name: api-website
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/webportifolio_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET_KEY: chave-secreta-docker-local-para-testes-muito-longa-32chars
      GOOGLE_CLIENT_ID: 343387992223-f8g2ocjl691sl46njle0ag9hgb93kf5g.apps.googleusercontent.com
      BREVO_API_KEY: xkeysib-chave-invalida-para-docker-local
      BREVO_SENDER_EMAIL: brunofragaa97@gmail.com

volumes:
  postgres-data:
